### ISSUE TITLE
No retina support for menu bar icon

### ISSUE THREAD

**Issue by JMY1000** [ghewgill/senotifier#28]
Title.

**Comment by grgar** [comment]
[Dupe of my issue from 2013.](https://github.com/ghewgill/senotifier/issues/19) 2 pull requests have been submitted by other people but haven't been merged. Seems the repo is abandoned. (I know your name too!)

**Comment by edelmanjm** [comment]
Oh hi I know you :). Might as well close this one then.

**Comment by JMY1000** [comment]
Oh hi I know you :). Might as well close this one then.
